site:
  title: OneCx Docs
  url: https://onecx.github.io/docs/
  start_page: index::index.adoc
content:
  sources:
    - url: . # common module containing just the main index
      branches: HEAD
    - url: https://github.com/onecx/docs-guides.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/docs-guides-documentation.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/docs-guides-angular.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/docs-guides-quarkus.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/docs-guides-bpmn.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-nx-plugins.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx-apps/onecx-document-management.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx-apps/onecx-document-management-svc.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx-apps/onecx-document-management-ui.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx-apps/onecx-document-management-bff.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-quarkus.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-tenant.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-tenant-svc.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-product-store.git
      branches: [HEAD]
      start_path: docs      
    - url: https://github.com/onecx/onecx-product-store-svc.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-product-store-bff.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-product-store-operator.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-product-store-mfe-operator.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-product-store-ms-operator.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-welcome.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-welcome-svc.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-welcome-bff.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-theme.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-theme-svc.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/onecx/onecx-theme-bff.git
      branches: [HEAD]
      start_path: docs
ui:
  bundle:
    url: https://github.com/onecx/docs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
urls:
  latest_version_segment: current
asciidoc:
  attributes:
    sourcemap: true
    kroki-fetch-diagram: true
  extensions:
    - ./extensions/bpmn-js.js
    - asciidoctor-kroki
